version: "3.9" 
services:
  app-exec:
    build: ./app-exec/
    container_name: app-exec
    logging:
        options:
            max-size: 200m
    #ports:
    #  - "80:80"
    volumes:
      - files:/var/www/html/files
    restart: unless-stopped
  app-nginx:
    build: ./app-nginx/
    container_name: app-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - files:/usr/share/nginx/html
volumes:
  files: