version: "3.9" 
services:
  app-exec:
    build: ./app-exec/
    container_name: app-exec
    logging:
        options:
            max-size: 100m
    ports:
      - "80:80"
    volumes:
      - files:/var/www/html/files
    restart: always
  #app-nginx:
    #build: ./app-ngin/
    #container_name: app-nginx
    #restart: always
volumes:
  files:
    #external: true